name: Build Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ğŸš¦Checkout repository
        uses: actions/checkout@v3

      - name: â˜•Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: ğŸš¨Run all checks
        run: ./gradlew test

      - name: ğŸ“‹Collect reports
        run: ./gradlew detektMergeReports koverCollectReports --parallel

      - name: â¬†Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: |
            ./kotlinify-core/build/reports/tests
            ./kotlinify-idea-plugin/build/reports/tests
        if: ${{ failure() }}

      - name: â˜‚Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          directory: ./build/reports/kover
          files: kotlinify-core.xml,kotlinify-idea-plugin.xml
          fail_ci_if_error: true

      - name: â¬†Upload coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: kover
          path: ./build/reports/kover
        if: ${{ always() }}

  mutation-test:
    needs: [ check ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 15
    steps:
      - name: ğŸš¦Checkout repository
        uses: actions/checkout@v3

      - name: âœ”Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: ğŸš¨Run mutation test
        run: ./gradlew :kotlinify-core:pitest

      - name: â¬†Upload mutation coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: pitest
          path: ./kotlinify-core/build/reports/pitest

  build-core:
    needs: [ check ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ğŸš¦Checkout repository
        uses: actions/checkout@v3

      - name: âœ”Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: ğŸ› Build module
        run: ./gradlew :kotlinify-core:build

  build-idea-plugin:
    needs: [ check ]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ğŸš¦Checkout repository
        uses: actions/checkout@v3

      - name: âœ”Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: âš™Export properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"

          echo "::set-output name=pluginVerifierHomeDir::~/.pluginVerifier"

          ./gradlew listProductsReleases

      - name: âš™Setup plugin verifier IDEs cache
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('build/listProductsReleases.txt') }}

      - name: âœ”Check the binary compatibilityï¸
        run: ./gradlew :kotlinify-idea-plugin:runPluginVerifier -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}

      - name: â¬†Upload IntelliJ Plugin Verifier results
        uses: actions/upload-artifact@v2
        with:
          name: pluginVerifier
          path: ./kotlinify-idea-plugin/build/reports/pluginVerifier
        if: ${{ always() }}

      - name: âš™Prepare plugin artifact
        id: artifact
        shell: bash
        run: |
          cd ./kotlinify-idea-plugin/build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content
          echo "::set-output name=filename::${FILENAME:0:-4}"

      - name: â¬†Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./kotlinify-idea-plugin/build/distributions/content/*/*
