name: Build Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checkout current repository
      - name: Checkout repository üö¶
        uses: actions/checkout@v3

      # Setup Java 11 environment
      - name: Setup Java 11 ‚òï
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      # Run all checks in thi project
      - name: Run all checks üö®
        run: ./gradlew test

      # Collect detekt and kover reports from all modules
      - name: Collect reports üìã
        run: ./gradlew detektMergeReports koverCollectReports --parallel

      # Upload test reports
      - name: Upload test reports ‚¨ÜÔ∏è
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: |
            ./kotlinify-core/build/reports/tests
            ./kotlinify-idea-plugin/build/reports/tests
        if: ${{ always() }}

      # Upload coverage reports to Codecov
      - name: Upload coverage reports ‚òÇÔ∏è
        uses: codecov/codecov-action@v2
        with:
          directory: ./build/reports/kover
          files: kotlinify-core.xml,kotlinify-idea-plugin.xml
          fail_ci_if_error: true
          verbose: true

      # Upload coverage reports as an Artifact
      - name: Upload coverage reports ‚¨ÜÔ∏è
        uses: actions/upload-artifact@v2
        with:
          name: kover
          path: ./build/reports/kover
        if: ${{ always() }}

  build-core:
    needs: [ check ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Check out current repository
      - name: Checkout repository üö¶
        uses: actions/checkout@v3

      # Validate gradle wrapper
      - name: Validate Gradle Wrapper ‚úî
        uses: gradle/wrapper-validation-action@v1

      # Build :kotlinify-core module
      - name: Build module üõ†Ô∏è
        run: ./gradlew :kotlinify-core:build

  build-idea-plugin:
    needs: [ check ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Check out current repository
      - name: Checkout repository üö¶
        uses: actions/checkout@v3

      # Validate gradle wrapper
      - name: Validate gradle wrapper ‚úî
        uses: gradle/wrapper-validation-action@v1

      # Set environment variables
      - name: Export properties ‚öôÔ∏è
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"

          echo "::set-output name=pluginVerifierHomeDir::~/.pluginVerifier"

          ./gradlew listProductsReleases

      # Cache Plugin Verifier IDEs
      - name: Setup plugin verifier IDEs cache ‚öôÔ∏è
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('build/listProductsReleases.txt') }}

      # Run the IntelliJ Plugin Verifier tool
      - name: Check the binary compatibility ‚úîÔ∏è
        run: ./gradlew :kotlinify-idea-plugin:runPluginVerifier -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}

      # Upload results of the IntelliJ Plugin Verifier
      - name: Upload IntelliJ Plugin Verifier results ‚¨ÜÔ∏è
        uses: actions/upload-artifact@v2
        with:
          name: pluginVerifier
          path: ./kotlinify-idea-plugin/build/reports/pluginVerifier
        if: ${{ always() }}

      # Prepare plugin archive content for creating artifact
      - name: Prepare plugin artifact ‚öôÔ∏è
        id: artifact
        shell: bash
        run: |
          cd ./kotlinify-idea-plugin/build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content
          echo "::set-output name=filename::${FILENAME:0:-4}"

      # Upload already-built plugin as an artifact for downloading
      - name: Upload artifact ‚¨ÜÔ∏è
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./kotlinify-idea-plugin/build/distributions/content/*/*
