name: Find License Compliance and Security Issues

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.txt'

jobs:
  fossa:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ğŸš¦Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ”Run FOSSA lisence scan
        uses: fossas/fossa-action@v1.1.1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

      - name: ğŸš¨Run FOSSA test
        uses: fossas/fossa-action@v1.1.1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
